services:
    web:
        build: .
        restart: unless-stopped
        depends_on:
            -   db
        ports:
            - "5000:5000"
        env_file:
            -   .env
    db:
        image: postgres:16.3-alpine
        restart: unless-stopped
        env_file:
            -   .env
        volumes:
            -   postgres_data:/var/lib/postgresql/data
        ports:
            -   "5432:5432"

volumes:
    postgres_data:
